import React, { useState, useEffect } from "react";
import PropTypes from "prop-types";

import { Comment } from "semantic-ui-react";
import ScrollView from "../common/ScrollView";
import Loader from "../common/Loader";

import { formatDateToText } from "../../utils/dateTime";
import { truncateString } from "../../utils/string";
import db from "../../db.json";

const HistoryItem = ({ conversation, index }) => {
  const { recipient, recentMessage } = conversation;
  const backgroundColor = index % 2 ? "#F5F5F5" : "#FFF";

  function openConversation() {
    // Open selected conversation in ConversationPane
    // Use conversation.id to identify selected conversation
  }

  // NB: Current avatars generated by faker do not render. Using a generic image for all renders.
  return (
    <Comment
      style={{ ...styles.historyItem, backgroundColor }}
      onClick={openConversation}
    >
      <Comment.Avatar
        as='a'
        src={"https://react.semantic-ui.com/images/avatar/small/stevie.jpg"}
      />
      <Comment.Content>
        <Comment.Author>{recipient.name}</Comment.Author>
        <Comment.Metadata>
          <div>{formatDateToText(recentMessage.time)}</div>
        </Comment.Metadata>
        <Comment.Text>{truncateString(recentMessage.text, 30)}</Comment.Text>
      </Comment.Content>
    </Comment>
  );
};

HistoryItem.propTypes = {
  conversation: PropTypes.object.isRequired,
  index: PropTypes.number.isRequired,
};

const HistoryPane = () => {
  const [loading, setLoading] = useState(true);
  const [history, setHistory] = useState([]);

  const fetchData = () => {
    setHistory(db.history);
    setLoading(false);
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return loading ? (
    <Loader />
  ) : (
    <div className='HistoryPane' style={styles.historyPane}>
      <ScrollView style={styles.historyFeed}>
        {history.map((convo, index) => (
          <HistoryItem key={convo.id} conversation={convo} index={index} />
        ))}
      </ScrollView>
    </div>
  );
};

export default HistoryPane;

const styles = {
  historyPane: {
    height: "inherit",
    backgroundColor: "#FFF",
  },
  historyFeed: {
    height: "inherit",
    padding: "1rem",
    marginBottom: "100px",
  },
  historyItem: {
    padding: "1rem",
  },
};
